In [50]:
import numpy as np
import pandas as pd

In [3]:
# произведение матриц

A = np.random.randint(5, 12, (3,3))
B = np.random.randint(-2, 4, (3,3))

print(f'A: {A}')
print(f'B: {B}')


A: [[ 9 11  6]
 [10  5 10]
 [11 11  6]]
B: [[-1  3 -1]
 [-2  2  3]
 [ 3  1  1]]


In [5]:
# Поэлементное умножение
A * B

array([[ -9,  33,  -6],
       [-20,  10,  30],
       [ 33,  11,   6]])

In [6]:
# тип np.matrix

A_m = np.matrix(A)
B_m = np.matrix(B)

print(A_m * B_m)

[[-13  55  30]
 [ 10  50  15]
 [-15  61  28]]


In [7]:
# Матричное умножение
np.dot(A, B)

array([[-13,  55,  30],
       [ 10,  50,  15],
       [-15,  61,  28]])

In [8]:
# Матричное умножение
A @ B

array([[-13,  55,  30],
       [ 10,  50,  15],
       [-15,  61,  28]])

In [9]:
# Порядок умножения AB != BA
B @ A

array([[10, -7, 18],
       [35, 21, 26],
       [48, 49, 34]])

In [10]:
# Умножение прямоугольных матриц возможно не в любом порядке
A = np.random.randint(5, 12, (3,5))
B = np.random.randint(-2, 4, (5,2))

print('A:\n',A)
print('B:\n',B)

A:
 [[ 9  9  9 11  5]
 [ 6  8  5  7 10]
 [ 6  9 10  5  9]]
B:
 [[ 1 -1]
 [ 3  1]
 [ 1  2]
 [ 1  3]
 [ 0  1]]


In [11]:
# Умножение прямоугольных матриц возможно не в любом порядке
A @ B

array([[56, 56],
       [42, 43],
       [48, 47]])

In [12]:
# Умножение прямоугольных матриц возможно не в любом порядке
B @ A

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

In [13]:
# размер произведения матриц
print('shape of A:', np.shape(A))
print('shape of B:', np.shape(B))
print('shape of AB:', np.shape(A @ B))

shape of A: (3, 5)
shape of B: (5, 2)
shape of AB: (3, 2)


In [14]:
# умножение на специальные матрицы
A = np.random.randint(-4, 4, (4,4))
D = np.diag([1,2,0, -1])

print('A:\n',A)
print('D:\n',D)
print('AD:\n',A @ D)
print('DA:\n',D @ A)

A:
 [[-2  2 -2  0]
 [-4 -3  1  1]
 [ 0 -1 -1  0]
 [-1 -4  1  2]]
D:
 [[ 1  0  0  0]
 [ 0  2  0  0]
 [ 0  0  0  0]
 [ 0  0  0 -1]]
AD:
 [[-2  4  0  0]
 [-4 -6  0 -1]
 [ 0 -2  0  0]
 [-1 -8  0 -2]]
DA:
 [[-2  2 -2  0]
 [-8 -6  2  2]
 [ 0  0  0  0]
 [ 1  4 -1 -2]]


In [17]:
# умножение на одномерный массив numpy
A = np.array([[1,0,1],[1,1,1]])
b = np.array([-3,4,5])

print('A:\n',A)
print('b:\n',b)

A @ b

A:
 [[1 0 1]
 [1 1 1]]
b:
 [-3  4  5]


array([2, 6])

In [18]:
b @ A

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [29]:
# матрица Грама ортогональной системы векторов
x = np.array([1,1,1])
y = np.array([1,0,-1])
z = np.array([-1,2,-1])
A = np.array([x,y,z]).T

print (A, type(A))

[[ 1  1 -1]
 [ 1  0  2]
 [ 1 -1 -1]] <class 'numpy.ndarray'>


In [30]:
# матрица Грама ортогональной системы векторов
print(f'Матрица Грама: \n{A.T @ A}')

Матрица Грама: 
[[3 0 0]
 [0 2 0]
 [0 0 6]]


In [32]:
# матрица Грама ортонормированной системы векторов
x_norm = x / np.linalg.norm(x)
y_norm = y / np.linalg.norm(y)
z_norm = z / np.linalg.norm(z)
A_norm = np.array([x_norm, y_norm, z_norm])

print (A_norm, type(A_norm))

[[ 0.57735027  0.57735027  0.57735027]
 [ 0.70710678  0.         -0.70710678]
 [-0.40824829  0.81649658 -0.40824829]] <class 'numpy.ndarray'>


In [33]:
# матрица Грама ортонормированной системы векторов
A_norm @ A_norm.T

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [34]:
# ортонормированные системы рулят! :)
np.round(A_norm @ A_norm.T,1)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Практика

Даны матрица  и вектор х:

A = np.array([[5,-1,3,1,2], [-2,8,5,-1,1]])

x = np.array([1,2,3,4,5])

Найдите произведение матрицы A и вектора х в том порядке, в котором их можно умножить.

В качестве ответа запишите координаты получившегося вектора через запятую, без пробелов. Пример ввода ответа: 1,1.

In [116]:
A = np.array([[5,-1,3,1,2], [-2,8,5,-1,1]])
x = np.array([1,2,3,4,5])

c = A @ x.T
print(c)

[26 30]


Даны две матрицы:

A = np.array([[1,9,8,5], [3,6,3,2], [3,3,3,3], [0,2,5,9], [4,4,1,2]])

B = np.array([[1,-1,0,1,1], [-2,0,2,-1,1]])

Найдите произведение матриц  и  в том порядке, в котором их можно умножить.

В качестве ответа через запятую, без пробелов запишите элемент чётвертого столбца первой строки.

In [103]:
A = np.array([[1,9,8,5], [3,6,3,2], [3,3,3,3], [0,2,5,9], [4,4,1,2]])
B = np.array([[1,-1,0,1,1], [-2,0,2,-1,1]])
print(A.shape)
print(B.shape)

(5, 4)
(2, 5)


In [106]:
C = B @ A
print(f'Произведение матриц A и B: \n{C}')
print(C[0,3])

Произведение матриц A и B: 
[[  2   9  11  14]
 [  8 -10 -14 -11]]
14


Дана система векторов:

x = np.array([1,2,1,0,4])

y = np.array([2,1,-1,1,0])

z = np.array([-1,1,-1,0,0])

Составьте матрицу A, расположив векторы x, y, z в строках. Найдите матрицу Грама G (матрицу скалярных произведений столбцов матрицы A) системы векторов x, y, z.

Чему равна полученная матрица Грама ?

In [45]:
x = np.array([1,2,1,0,4])
y = np.array([2,1,-1,1,0])
z = np.array([-1,1,-1,0,0])

In [49]:
A = np.array([x, y, z])
print(A)

G = A.T @ A

print(f'Матрица Грама: \n{G}')

[[ 1  2  1  0  4]
 [ 2  1 -1  1  0]
 [-1  1 -1  0  0]]
Матрица Грама: 
[[ 6  3  0  2  4]
 [ 3  6  0  1  8]
 [ 0  0  3 -1  4]
 [ 2  1 -1  1  0]
 [ 4  8  4  0 16]]


В салоне красоты «Феи ножниц» работают восемь стилистов: Аня, Борис, Вика, Галя, Дима, Егор, Женя и Юра. 

Вам предоставлены две таблицы (DataFrame): Count_DF и Price_DF.

* В DataFrame Count_DF содержится информация по количеству услуг, оказанных каждым стилистом за апрель.
* В DataFrame Price_DF содержится информация по стоимости услуг у каждого стилиста в тысячах рублей.

In [61]:
Count_DF = pd.DataFrame({
    'Женские стрижки': [10, 2, 12, 4, 6, 10, 22, 7], 
    'Мужские стрижки': [5, 21, 12, 8, 25, 3, 1, 0], 
    'Окрашивания':[12, 3, 0, 18, 27, 2, 4, 31],
    'Укладка':[15, 25, 30, 14, 25, 17, 25, 31],
    'Уход':[10, 6, 4, 5, 18, 12, 20, 28]
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)

Price_DF = pd.DataFrame({
    'Женские стрижки': [2, 1.8, 2, 1.8, 2.5, 5, 1.1, 4.5], 
    'Мужские стрижки': [1.5, 2.5, 2, 1.2, 3.5, 5, 1, 4], 
    'Окрашивания':[1, 1, 0, 2.8, 2, 3, 1.5, 2.5],
    'Укладка':[0.8, 1, 0.5, 0.8, 1, 2, 0.5, 1],
    'Уход':[1, 1, 2, 2, 1.5, 2.5, 1.7, 2] 
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)

print(Count_DF)
print()
print(Price_DF)

       Женские стрижки  Мужские стрижки  Окрашивания  Укладка  Уход
Аня                 10                5           12       15    10
Борис                2               21            3       25     6
Вика                12               12            0       30     4
Галя                 4                8           18       14     5
Дима                 6               25           27       25    18
Егор                10                3            2       17    12
Женя                22                1            4       25    20
Юра                  7                0           31       31    28

       Женские стрижки  Мужские стрижки  Окрашивания  Укладка  Уход
Аня                2.0              1.5          1.0      0.8   1.0
Борис              1.8              2.5          1.0      1.0   1.0
Вика               2.0              2.0          0.0      0.5   2.0
Галя               1.8              1.2          2.8      0.8   2.0
Дима               2.5              3.5        

Найдите вектор дохода салона по стилистам, если за каждую услугу стилисты платят салону определённую «комиссию».

Вектор комиссий: com = np.array([0.2, 0.2, 0.3, 0.1, 0.1]).

Выберите координаты вектора прибыли салона:

In [57]:
# Вектор комиссии
com = np.array([0.2, 0.2, 0.3, 0.1, 0.1])

In [59]:
# Переводим df в виде матриц
Count_A = Count_DF.values
Price_B = Price_DF.values

print(Count_A)
print()
print(Price_B)

[[10  5 12 15 10]
 [ 2 21  3 25  6]
 [12 12  0 30  4]
 [ 4  8 18 14  5]
 [ 6 25 27 25 18]
 [10  3  2 17 12]
 [22  1  4 25 20]
 [ 7  0 31 31 28]]

[[2.  1.5 1.  0.8 1. ]
 [1.8 2.5 1.  1.  1. ]
 [2.  2.  0.  0.5 2. ]
 [1.8 1.2 2.8 0.8 2. ]
 [2.5 3.5 2.  1.  1.5]
 [5.  5.  3.  2.  2.5]
 [1.1 1.  1.5 0.5 1.7]
 [4.5 4.  2.5 1.  2. ]]


In [86]:
# Поэлементное умножение количества услуг на стоимость
total_revenue = Count_A * Price_B
print(total_revenue)

print()

income = np.dot(total_revenue, com)
print(f'Доход салона: {income}')

[[20.   7.5 12.  12.  10. ]
 [ 3.6 52.5  3.  25.   6. ]
 [24.  24.   0.  15.   8. ]
 [ 7.2  9.6 50.4 11.2 10. ]
 [15.  87.5 54.  25.  27. ]
 [50.  15.   6.  34.  30. ]
 [24.2  1.   6.  12.5 34. ]
 [31.5  0.  77.5 31.  56. ]]

Доход салона: [11.3  15.22 11.9  20.6  41.9  21.2  11.49 38.25]


Найдите вектор дохода стилистов.

Выберите координаты полученного вектора:

In [101]:
# Доход стилистов за вычетом коммиссии салона (доля за одну услугу - комиссия (np.ones(5) - com))
commissioned_revenue = (Count_A * Price_B) @ (np.ones(5) - com)
print(f'Доход cтилистов: {commissioned_revenue}')

Доход cтилистов: [ 50.2   74.88  59.1   67.8  166.6  113.8   66.21 157.75]
