In [2]:
import numpy as np

s = np.array([33,65,50,45])

print(s)
print(len(s))
print(s[2])

[33 65 50 45]
4
50


In [3]:
t = np.array([12, 14, 17, 19, 24, 28, 31, 31, 27, 22, 17, 13])

print(t[5])
print(t[0])
print(t[2])
print(t[6])

28
12
17
31


In [4]:
a = np.array([10,8,5,1])
b = np.array([5,15,9,7])

print(f'Сложение векторов:{a + b}')
print(f'Разность векторов:{a - b}')

Сложение векторов:[15 23 14  8]
Разность векторов:[ 5 -7 -4 -6]


In [5]:
a = np.array([120,45,68])
omega = 0.2
c = a * omega
print(f'Умножение вектора на число:{c}')

Умножение вектора на число:[24.   9.  13.6]


In [6]:
p = np.array([2,4,5]) # premium
v = np.array([8,10,2]) # vip
s = np.array([0,12,7]) # simple

coef_p = 500
coef_v = 100
coef_s = 0

m = coef_p * p + coef_v * v + coef_s * s
print(f'Линейная комбинация с тремя коэффициентами:{m}')

Линейная комбинация с тремя коэффициентами:[1800 3000 2700]


In [7]:
x = np.array([-3, 1])
y = np.array([-2, 1])

c1 =4
c2 =-1

z = c1 * x + c2 * y
print(z)

[-10   3]


In [8]:
a = np.array([65,70,120,30])
w = np.array([0.4,0.4,0.2,0.8])

print(f'Скалярное произведение (умножение):{np.dot(a,w)}')

Скалярное произведение (умножение):102.0


# Матрицы

In [9]:
A = np.array([[1,-5,3],
              [2,2,1],
              [0,3,1],
              [4,4,12]
              ])

print(A)
print(f'Размер:{A.shape}')
print(f'a_23={A[1,2]}')
print(f'a_32={A[2,1]}')
print(f'a_33={A[2,2]}')

[[ 1 -5  3]
 [ 2  2  1]
 [ 0  3  1]
 [ 4  4 12]]
Размер:(4, 3)
a_23=1
a_32=3
a_33=1


In [10]:
A = np.matrix('5,6,-1;8,2,3;12,7,14')

print(f'Матрица: \n{A}')
print(f'Транспонированная матрица (перевернутая): \n{A.T}')

Матрица: 
[[ 5  6 -1]
 [ 8  2  3]
 [12  7 14]]
Транспонированная матрица (перевернутая): 
[[ 5  8 12]
 [ 6  2  7]
 [-1  3 14]]


# Умножение матриц

In [11]:
A = np.matrix("1, -5; 2, 2; 0, 3")
B = np.matrix("3, 1, 0; -1, 0, 2")

In [12]:
A

matrix([[ 1, -5],
        [ 2,  2],
        [ 0,  3]])

In [13]:
B

matrix([[ 3,  1,  0],
        [-1,  0,  2]])

In [14]:
# Умножение матрицы A на B
np.dot(A, B)

matrix([[  8,   1, -10],
        [  4,   2,   4],
        [ -3,   0,   6]])

In [15]:
# Умножение матрицы B на A
np.dot(B, A)

matrix([[  5, -13],
        [ -1,  11]])

In [16]:
# Умножние квадратных матриц (2, 2)
A = np.matrix('2,3; 1,3')
B = np.matrix('4,1; 1,0')

print(np.dot(A, B))
print()
print(np.dot(B, A))

[[11  2]
 [ 7  1]]

[[ 9 15]
 [ 2  3]]


In [17]:
A = np.matrix('1,-1,2,4,0;8,2,0,5,3;0,1,2,1,2')
B = np.matrix('1,0,1,0;0,0,2,-1;1,0,1,1;0,1,1,1;1,1,0,-1')
print(A)
print()
print(B)

[[ 1 -1  2  4  0]
 [ 8  2  0  5  3]
 [ 0  1  2  1  2]]

[[ 1  0  1  0]
 [ 0  0  2 -1]
 [ 1  0  1  1]
 [ 0  1  1  1]
 [ 1  1  0 -1]]


In [18]:
C = np.dot(A, B)
print(C)
print()
print(C[0,1])
print(C[2,3])

[[ 3  4  5  7]
 [11  8 17  0]
 [ 4  3  5  0]]

4
0


# Вычисление обратной матрицы

In [19]:
A = np.matrix('1,2,3;4,5,6;7,8,10')
A

matrix([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8, 10]])

In [20]:
np.linalg.inv(A) # Существует

matrix([[-0.66666667, -1.33333333,  1.        ],
        [-0.66666667,  3.66666667, -2.        ],
        [ 1.        , -2.        ,  1.        ]])

In [21]:
A = np.matrix('1,2;3,7')
np.linalg.inv(A) # Существует

matrix([[ 7., -2.],
        [-3.,  1.]])

In [22]:
A = np.matrix('1,1; 0,0')
np.linalg.inv(A) # НЕ Существует

LinAlgError: Singular matrix

In [ ]:
A = np.matrix('5,7; 3,-2')
np.linalg.inv(A) # Существует

# Определитель матриц

In [ ]:
A = np.matrix('6,-3;9,11')
np.linalg.det(A)

In [ ]:
# Вырожденная матрица
A_bad = np.matrix('1,1;0,0')
np.linalg.det(A_bad) # = 0

In [ ]:
A = np.matrix ("1, 2, 3; 4, 5, 6 ; 7, 8, 10")
np.linalg.det(A)

In [ ]:
A = np.matrix('2,0,0;0,1,0;0,0,4')
A_1 = np.linalg.inv(A)

print(f'det(A)={round(np.linalg.det(A))}')
print(f'det(A)={np.linalg.det(A_1):3f}')

In [ ]:
# Определяем ранг матрицы
A = np.matrix('1,2,3;1,-1,0;2,3,5')
rank_A = np.linalg.matrix_rank(A)
print(f"Ранг матрицы: {rank_A}")

# Определяем ранг матрицы
B = np.matrix('1,2;2,4')
rank_B = np.linalg.matrix_rank(B)
print(f"Ранг матрицы: {rank_B}")

In [ ]:
# Если ранг меньше числа столбцов, векторы линейно зависимы
if rank_B < A.shape[1]:
    print("Векторы линейно зависимы")
else:
    print("Векторы линейно независимы")

In [ ]:
a = np.array([4,1,0])
b = np.array([-1,4,0])
c = np.array([0,0,1])
A = np.array([a,b,c])

rank = np.linalg.matrix_rank(A)
# Если ранг меньше числа столбцов, векторы линейно зависимы
if rank < A.shape[1]:
    print("Векторы линейно зависимы")
else:
    print("Векторы линейно независимы")

In [ ]:
# Ортогональны если 0
print("(a,b):", np.dot(a,b))
print("(a,c):", np.dot(a,c))
print("(b,c):", np.dot(b,c))

In [ ]:
v1 = np.array([-1,2,-7,9]).T
v2 = np.array([2,8,2,-1]).T

print(v1 @ v2)

In [ ]:
A = np.matrix('1,1;1,2')
G = A.T @ A
print(G)

In [ ]:
A = np.matrix('1,2;3,7')
print(np.linalg.det(A))

A_inv = np.linalg.inv(A)
print(A_inv)

In [ ]:
v1 = np.array([2,10,-2]).T
v2 = np.array([3,2,-2]).T
v3 = np.array([8,14,-6]).T
A = np.array([v1,v2,v3]).T
print(A)

print(np.linalg.matrix_rank(A))

In [ ]:
A = np.matrix('5,1;10,2')
print(A)

rank = np.linalg.matrix_rank(A)

n_var = A.shape[1]

if rank == n_var:
    print('Система имеет только одно тривиальное решение: (w1 = w2 = 0)')
elif rank < n_var:
    print('Система имеет множество решений, включая нетривиальные')

In [ ]:
A = np.matrix('5,1,3;0,2,8;10,0,2')
print(A)
print(np.linalg.matrix_rank(A))

In [ ]:
A = np.matrix('1,1;1,2')
A_ex = np.matrix('1,1,1;1,2,2')
print(A)
print(A_ex)
print(np.linalg.matrix_rank(A_ex))
print(np.linalg.matrix_rank(A))

In [ ]:
A_ext = np.matrix('1,1,2;1,7,3')
A = np.matrix('1,1;1,7')
B_ext = np.matrix('2,2,4;2,14,6')
B = np.matrix('2,2;2,14')

print(A_ext)
print(B_ext)

print(np.linalg.matrix_rank(A_ext))
print(np.linalg.matrix_rank(B_ext))
print(np.linalg.matrix_rank(A) == np.linalg.matrix_rank(A_ext))
print(np.linalg.matrix_rank(B) == np.linalg.matrix_rank(B_ext))

In [23]:
from Math_algorithms import gauss_algorithm

# Матрица коэффициентов
A = np.array([
    [2,1,1],
    [4,3,1],
    [6,5,2]
    ])

# Правая часть
b = [5,6,8]

# Решение
solution = gauss_algorithm(A, b)
print("Решение системы методом Гаусса:")
for i, x_i in enumerate(solution):
    print(f"x{i+1} = {x_i}")

Решение системы методом Гаусса:
x1 = 3.5
x2 = -3.0
x3 = 1.0


In [24]:
A = np.array([
    [4,7,-1],
    [-4,2,5],
    [0,9,4]
])

A_ext = A = np.array([
    [4,7,-1,7],
    [-4,2,5,3],
    [0,9,4,10]
])

print(np.linalg.matrix_rank(A))
print(A.shape[1])
print(np.linalg.matrix_rank(A_ext))
print(A_ext.shape[1])

2
4
2
4


In [27]:
# Система не имеет точных решений 
A = np.array([[1,1], 
             [1,2], 
             [1,1]])

A_ext = np.array([[1,1,1], 
             [1,2,2], 
             [1,1,12]])

print(f'rk(A) = {np.linalg.matrix_rank(A)}')
print(f'rk(A_ext) = {np.linalg.matrix_rank(A_ext)}')

rk(A) = 2
rk(A_ext) = 3


In [53]:
A = np.array([[1,1,1],
              [1,1,1],
              [0,1,1]])

print(np.linalg.matrix_rank(A))

A_ext = np.array([[1,1,1,0],
              [1,1,1,0],
              [0,1,1,0]])

print(np.linalg.matrix_rank(A_ext))

2
2


In [55]:
A = np.array([[1,2],[-3,1],[1,2],[1,-1]])
b = np.array([1,4,5,0])
print(A.T)

G = A.T @ A
print(G)

[[ 1 -3  1  1]
 [ 2  1  2 -1]]
[[12  0]
 [ 0 10]]


In [56]:
print(np.linalg.det(G.T))

120.00000000000009


In [61]:
ATA_inv = np.linalg.inv(G)
print(ATA_inv)

[[0.08333333 0.        ]
 [0.         0.1       ]]


In [64]:
diag = np.diag(G.T)
print(diag)

[12 10]


# Полиноминальная регрессия

In [25]:
A = np.array([
    [1, 1, 1, 1],
    [1, 3, -2, 1],
    [1, 9, 4, 1]
]).T

y = np.array([4,5,2,2])

w_hat = np.linalg.inv(A.T @ A) @ A.T @ y
print(w_hat)

[2.4        0.46666667 0.13333333]


In [26]:
A = np.array([
    [1, 1, 1, 1, 1, 1, 1],
    [1, 3, -2, 1, 5, 13, 1],
    [3, 4, 5, -2, 4, 11, 3],
    [1, 9, 4, 1, 25, 169, 1],
    [3, 12, -10, -2, 20, 143, 3],
    [9, 16, 25, 4, 16, 121, 9]
    
]).T

y = np.array([4, 5, 2, 2, 6, 8, -1])

w_hat = np.linalg.inv(A.T @ A) @ A.T @ y
print(w_hat)

[-2.25799015  2.37672337 -0.1322068  -0.10208147 -0.26501791  0.29722471]
